# Generated by Django 3.1 on 2021-01-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='content',
        ),
        migrations.RemoveField(
            model_name='training',
            name='title',
        ),
    ]
