# Generated by Django 3.1 on 2021-01-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210128_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrenchClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GermanClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpanishClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='italianleague',
            name='total_point',
        ),
        migrations.AlterField(
            model_name='italianleague',
            name='point',
            field=models.CharField(max_length=3),
        ),
        migrations.CreateModel(
            name='Premiership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.CharField(max_length=2)),
                ('win', models.CharField(max_length=2)),
                ('draw', models.CharField(max_length=2)),
                ('lost', models.CharField(max_length=2)),
                ('goalf', models.CharField(max_length=3)),
                ('goala', models.CharField(max_length=3)),
                ('total_points', models.CharField(max_length=3)),
                ('team_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='info.englishclubs')),
            ],
            options={
                'db_table': 'Premiership',
            },
        ),
        migrations.CreateModel(
            name='Ligue1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.CharField(max_length=2)),
                ('win', models.CharField(max_length=2)),
                ('draw', models.CharField(max_length=2)),
                ('lost', models.CharField(max_length=2)),
                ('goalf', models.CharField(max_length=3)),
                ('goala', models.CharField(max_length=3)),
                ('total_points', models.CharField(max_length=3)),
                ('team_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='info.frenchclubs')),
            ],
            options={
                'db_table': 'Ligue1',
            },
        ),
        migrations.CreateModel(
            name='Laliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.CharField(max_length=2)),
                ('win', models.CharField(max_length=2)),
                ('draw', models.CharField(max_length=2)),
                ('lost', models.CharField(max_length=2)),
                ('goalf', models.CharField(max_length=3)),
                ('goala', models.CharField(max_length=3)),
                ('total_points', models.CharField(max_length=3)),
                ('team_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='info.spanishclubs')),
            ],
            options={
                'db_table': 'Laliga',
            },
        ),
        migrations.CreateModel(
            name='Bundesliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.CharField(max_length=2)),
                ('win', models.CharField(max_length=2)),
                ('draw', models.CharField(max_length=2)),
                ('lost', models.CharField(max_length=2)),
                ('goalf', models.CharField(max_length=3)),
                ('goala', models.CharField(max_length=3)),
                ('total_points', models.CharField(max_length=3)),
                ('team_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='info.germanclubs')),
            ],
            options={
                'db_table': 'Bundesliga',
            },
        ),
    ]
