# Generated by Django 3.1 on 2021-01-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210128_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundesliga',
            options={'verbose_name_plural': 'Bundesliga'},
        ),
        migrations.AlterModelOptions(
            name='englishclubs',
            options={'verbose_name_plural': 'English Clubs'},
        ),
        migrations.AlterModelOptions(
            name='frenchclubs',
            options={'verbose_name_plural': ' French Clubs'},
        ),
        migrations.AlterModelOptions(
            name='germanclubs',
            options={'verbose_name_plural': 'German Clubs'},
        ),
        migrations.AlterModelOptions(
            name='laliga',
            options={'verbose_name_plural': 'Laliga'},
        ),
        migrations.AlterModelOptions(
            name='ligue1',
            options={'verbose_name_plural': 'Ligue1'},
        ),
        migrations.AlterModelOptions(
            name='premiership',
            options={'verbose_name_plural': 'Premiership'},
        ),
        migrations.AlterModelOptions(
            name='spanishclubs',
            options={'verbose_name_plural': 'Spanish Clubs'},
        ),
        migrations.AlterModelTable(
            name='bundesliga',
            table=None,
        ),
        migrations.AlterModelTable(
            name='laliga',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ligue1',
            table=None,
        ),
        migrations.AlterModelTable(
            name='premiership',
            table=None,
        ),
    ]
