# Generated by Django 3.1 on 2021-02-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210128_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItalianLeague',
        ),
    ]
