# Generated by Django 3.1 on 2021-02-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_italianclubs_seriea'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seriea',
            table='SerieA',
        ),
    ]
