# Generated by Django 3.1 on 2021-02-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20210204_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriea',
            options={'verbose_name_plural': 'ItalinLeague'},
        ),
        migrations.AlterModelTable(
            name='seriea',
            table=None,
        ),
        migrations.CreateModel(
            name='ItalianSerieA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.CharField(max_length=2)),
                ('win', models.CharField(max_length=2)),
                ('draw', models.CharField(max_length=2)),
                ('lost', models.CharField(max_length=2)),
                ('goalf', models.CharField(max_length=3)),
                ('goala', models.CharField(max_length=3)),
                ('point', models.CharField(max_length=3)),
                ('team_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='info.italianclubs')),
            ],
            options={
                'verbose_name_plural': 'ItalinLeague',
            },
        ),
    ]
