# Generated by Django 3.1 on 2021-02-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20210204_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='italianseriea',
            options={'verbose_name_plural': 'ItalianLeague'},
        ),
    ]
