# Generated by Django 3.1 on 2021-02-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20210204_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItalianSerieA',
        ),
    ]
