# Generated by Django 3.1 on 2021-02-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_delete_italianseriea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SerieA',
        ),
    ]
