# Generated by Django 3.1 on 2021-02-04 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_delete_seriea'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItalianS',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('point', models.IntegerField()),
                ('team_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='info.italianclubs')),
            ],
            options={
                'verbose_name_plural': 'ItalinLeague',
            },
        ),
    ]
