# Generated by Django 3.1 on 2021-02-04 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_italians'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItalianS',
            new_name='ItalianSerieA',
        ),
    ]
