# Generated by Django 3.1 on 2021-02-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20210204_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItalianSerieA',
        ),
    ]
