# Generated by Django 3.1 on 2021-02-05 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_delete_italianseriea'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItalianSerieA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('point', models.IntegerField()),
                ('team_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='info.italianclubs')),
            ],
            options={
                'verbose_name_plural': 'ItalinLeague',
            },
        ),
    ]
