# Generated by Django 3.1 on 2021-02-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_italianseriea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='italianseriea',
            options={'verbose_name_plural': 'ItalianSerieA'},
        ),
    ]
