# Generated by Django 3.1 on 2021-02-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20210205_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='italianseriea',
            name='team_name',
            field=models.CharField(max_length=50),
        ),
    ]
