# Generated by Django 3.1 on 2021-02-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20210205_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItalianSerieA',
        ),
    ]
