# Generated by Django 3.1 on 2021-02-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_italianseriea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItalianSerieA',
        ),
    ]
