# Generated by Django 3.1 on 2021-02-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20210218_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundesliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Laliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ligue1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorldLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.CharField(max_length=2)),
                ('win', models.CharField(max_length=2)),
                ('draw', models.CharField(max_length=2)),
                ('lost', models.CharField(max_length=2)),
                ('goalf', models.CharField(max_length=3)),
                ('goala', models.CharField(max_length=3)),
                ('total_points', models.CharField(max_length=3)),
                ('team_name', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='info.englishclubs')),
            ],
            options={
                'verbose_name_plural': 'Premiership',
            },
        ),
        migrations.CreateModel(
            name='Premiership',
            fields=[
                ('worldleague_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='info.worldleague')),
            ],
            bases=('info.worldleague',),
        ),
    ]
