# Generated by Django 3.1 on 2021-02-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_bundesliga_laliga_ligue1_premiership_worldleague'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundesliga',
        ),
        migrations.DeleteModel(
            name='Laliga',
        ),
        migrations.DeleteModel(
            name='Ligue1',
        ),
        migrations.RemoveField(
            model_name='worldleague',
            name='team_name',
        ),
        migrations.DeleteModel(
            name='Premiership',
        ),
        migrations.DeleteModel(
            name='WorldLeague',
        ),
    ]
