# Generated by Django 3.1 on 2021-02-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20210218_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItalianSerieA',
        ),
    ]
