# Generated by Django 3.1 on 2021-02-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_bundesliga_italianseriea_laliga_ligue1_premiership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundesliga',
        ),
        migrations.DeleteModel(
            name='ItalianSerieA',
        ),
        migrations.DeleteModel(
            name='Laliga',
        ),
        migrations.DeleteModel(
            name='Ligue1',
        ),
        migrations.DeleteModel(
            name='Premiership',
        ),
    ]
