# Generated by Django 3.1 on 2021-02-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0036_bundesliga_italianseriea_laliga_league_ligue1_premiership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesliga',
            name='total_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='italianseriea',
            name='total_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='total_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ligue1',
            name='total_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='premiership',
            name='total_points',
            field=models.IntegerField(),
        ),
    ]
