# Generated by Django 3.1 on 2021-02-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0038_auto_20210222_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='italianseriea',
            name='league',
        ),
        migrations.RemoveField(
            model_name='italianseriea',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='laliga',
            name='league',
        ),
        migrations.RemoveField(
            model_name='laliga',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='ligue1',
            name='league',
        ),
        migrations.RemoveField(
            model_name='ligue1',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='premiership',
            name='league',
        ),
        migrations.RemoveField(
            model_name='premiership',
            name='team_name',
        ),
        migrations.DeleteModel(
            name='Bundesliga',
        ),
        migrations.DeleteModel(
            name='ItalianSerieA',
        ),
        migrations.DeleteModel(
            name='Laliga',
        ),
        migrations.DeleteModel(
            name='Ligue1',
        ),
        migrations.DeleteModel(
            name='Premiership',
        ),
    ]
