# Generated by Django 3.1 on 2021-02-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0040_bundesliga_italianseriea_laliga_ligue1_premiership'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundesliga',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='italianseriea',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laliga',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ligue1',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='premiership',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
