# Generated by Django 3.1 on 2021-02-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0042_bundesliga_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesliga',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.englishclubs'),
        ),
    ]
