# Generated by Django 3.1 on 2021-02-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0043_auto_20210223_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundesliga',
            name='team',
        ),
    ]
