# Generated by Django 3.1 on 2021-02-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0046_auto_20210223_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premiership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
                ('club', models.ForeignKey(default='club', on_delete=django.db.models.deletion.CASCADE, to='info.englishclubs')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.league')),
            ],
            options={
                'verbose_name_plural': 'Premiership',
            },
        ),
        migrations.CreateModel(
            name='Ligue1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.league')),
            ],
            options={
                'verbose_name_plural': 'Ligue1',
            },
        ),
        migrations.CreateModel(
            name='Laliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.league')),
            ],
            options={
                'verbose_name_plural': 'Laliga',
            },
        ),
        migrations.CreateModel(
            name='ItalianSerieA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.league')),
            ],
            options={
                'verbose_name_plural': 'ItalianSerieA',
            },
        ),
        migrations.CreateModel(
            name='Bundesliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.league')),
            ],
            options={
                'verbose_name_plural': 'Bundesliga',
            },
        ),
    ]
