# Generated by Django 3.1 on 2021-02-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0047_bundesliga_italianseriea_laliga_ligue1_premiership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesliga',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.league', verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='italianseriea',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.league', verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.league', verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='ligue1',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.league', verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='premiership',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.englishclubs', verbose_name='premiership'),
        ),
        migrations.AlterField(
            model_name='premiership',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.league', verbose_name='League'),
        ),
    ]
