# Generated by Django 3.1 on 2021-02-23 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0048_auto_20210223_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='laliga',
            name='team_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.spanishclubs', verbose_name='Laliga'),
        ),
    ]
