# Generated by Django 3.1 on 2021-02-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0050_turkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurkeyClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='turkey',
            name='club_name',
        ),
        migrations.AddField(
            model_name='turkey',
            name='team_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.turkeyclubs'),
        ),
    ]
