# Generated by Django 3.1 on 2021-02-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0051_auto_20210223_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turkey',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
