# Generated by Django 3.1 on 2021-02-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0053_auto_20210223_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laliga',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='premiership',
            name='club',
        ),
        migrations.RemoveField(
            model_name='premiership',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='turkey',
            name='total_points',
        ),
        migrations.AddField(
            model_name='bundesliga',
            name='team_name',
            field=models.CharField(default='bundesliga', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='italianseriea',
            name='team_name',
            field=models.CharField(default='italy', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='ligue1',
            name='team_name',
            field=models.CharField(default='french', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='premiership',
            name='team_name',
            field=models.CharField(default='english', max_length=50, unique=False),
        ),
        migrations.AlterField(
            model_name='bundesliga',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='italianseriea',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ligue1',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='premiership',
            name='point',
            field=models.IntegerField(),
        ),
    ]
