# Generated by Django 3.1 on 2021-02-23 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0054_auto_20210223_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiership',
            name='league',
        ),
        migrations.RemoveField(
            model_name='bundesliga',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='ligue1',
            name='team_name',
        ),
        migrations.AlterField(
            model_name='bundesliga',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='italianseriea',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='italianseriea',
            name='team_name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='info.italianclubs'),
        ),
        migrations.AlterField(
            model_name='ligue1',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turkey',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Laliga',
        ),
        migrations.DeleteModel(
            name='Premiership',
        ),
    ]
