# Generated by Django 3.1 on 2021-02-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0055_auto_20210223_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishclubs',
            name='club_name',
            field=models.CharField(max_length=50),
        ),
    ]
