# Generated by Django 3.1 on 2021-02-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0056_auto_20210223_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItalianSerieA',
        ),
    ]
