# Generated by Django 3.1 on 2021-02-23 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0057_delete_italianseriea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundesliga',
        ),
    ]
