# Generated by Django 3.1 on 2021-02-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0058_delete_bundesliga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ligue1',
        ),
    ]
