# Generated by Django 3.1 on 2021-02-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0059_delete_ligue1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnglishClubs',
        ),
        migrations.DeleteModel(
            name='FrenchClubs',
        ),
        migrations.DeleteModel(
            name='GermanClubs',
        ),
        migrations.DeleteModel(
            name='ItalianClubs',
        ),
        migrations.DeleteModel(
            name='SpanishClubs',
        ),
        migrations.DeleteModel(
            name='TurkeyClubs',
        ),
    ]
