# Generated by Django 3.1 on 2021-02-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0062_bundesliga_italianseriea_laliga_ligue1_premiership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundesliga',
            options={'verbose_name_plural': 'Bundesliga'},
        ),
        migrations.AlterModelOptions(
            name='italianseriea',
            options={'verbose_name_plural': 'ItalianSerie A'},
        ),
        migrations.AlterModelOptions(
            name='laliga',
            options={'verbose_name_plural': 'Laliga'},
        ),
        migrations.AlterModelOptions(
            name='ligue1',
            options={'verbose_name_plural': 'Ligue1'},
        ),
        migrations.AlterModelOptions(
            name='premiership',
            options={'verbose_name_plural': 'Premiership'},
        ),
        migrations.AlterModelOptions(
            name='turkey',
            options={'verbose_name_plural': 'Turkey'},
        ),
        migrations.RemoveField(
            model_name='laliga',
            name='point',
        ),
    ]
