# Generated by Django 3.1 on 2021-02-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0063_auto_20210224_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='laliga',
            name='points',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
