# Generated by Django 3.1 on 2021-02-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0064_laliga_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laliga',
            name='points',
        ),
    ]
