# Generated by Django 3.1 on 2021-02-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0065_remove_laliga_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='laliga',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
