# Generated by Django 3.1 on 2021-02-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0068_bundesliga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundesliga',
        ),
    ]
