# Generated by Django 3.1 on 2021-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0073_premiers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiers',
            options={'verbose_name_plural': 'Premier'},
        ),
        migrations.AddField(
            model_name='premiers',
            name='total_point',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
