# Generated by Django 3.1 on 2021-02-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0074_auto_20210224_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremierS',
        ),
    ]
