# Generated by Django 3.1 on 2021-02-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0076_premiers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremierS',
        ),
    ]
