# Generated by Django 3.1 on 2021-02-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0078_auto_20210224_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='italianseriea',
            options={'verbose_name_plural': 'ItalianSerie A'},
        ),
        migrations.RemoveField(
            model_name='laliga',
            name='point',
        ),
        migrations.AddField(
            model_name='laliga',
            name='points',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='bundesliga',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bundesliga',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='italianseriea',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='italianseriea',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='laliga',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ligue1',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ligue1',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='premiership',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='premiership',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='turkey',
            name='point',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turkey',
            name='team_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='EnglishClubs',
        ),
        migrations.DeleteModel(
            name='FrenchClubs',
        ),
        migrations.DeleteModel(
            name='GermanClubs',
        ),
        migrations.DeleteModel(
            name='ItalianClubs',
        ),
        migrations.DeleteModel(
            name='SpanishClubs',
        ),
        migrations.DeleteModel(
            name='TurkishClubs',
        ),
    ]
