# Generated by Django 3.1 on 2021-02-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0079_auto_20210224_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesliga',
            name='league',
            field=models.ForeignKey(default='bayern', on_delete=django.db.models.deletion.SET_DEFAULT, to='info.league', verbose_name='League'),
        ),
    ]
