# Generated by Django 3.1 on 2021-02-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0081_auto_20210224_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesliga',
            name='league',
            field=models.CharField(max_length=30),
        ),
    ]
