# Generated by Django 3.1 on 2021-02-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0082_auto_20210224_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundesliga',
        ),
    ]
