# Generated by Django 3.1 on 2021-02-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0084_bundesliga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesliga',
            name='played',
            field=models.CharField(default='bund', max_length=50),
        ),
        migrations.AlterField(
            model_name='bundesliga',
            name='team_name',
            field=models.CharField(default='bund', max_length=50),
        ),
    ]
