# Generated by Django 3.1 on 2021-02-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0086_auto_20210225_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundesliga',
            name='draw',
            field=models.CharField(default='bund', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bundesliga',
            name='goala',
            field=models.CharField(default='bund', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bundesliga',
            name='goalf',
            field=models.CharField(default='bund', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bundesliga',
            name='lost',
            field=models.CharField(default='bund', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='bundesliga',
            name='point',
            field=models.CharField(default='bund', max_length=50, unique=True),
        ),
    ]
