# Generated by Django 3.1 on 2021-02-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0091_premiership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiership',
            name='total_points',
        ),
        migrations.CreateModel(
            name='Ligue1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
                ('league', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.league', verbose_name='League')),
                ('team_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.frenchclubs')),
            ],
            options={
                'verbose_name_plural': 'Ligue!',
            },
        ),
        migrations.CreateModel(
            name='Laliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
                ('league', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.league', verbose_name='League')),
                ('team_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.spanishclubs')),
            ],
            options={
                'verbose_name_plural': 'Laliga',
            },
        ),
        migrations.CreateModel(
            name='ItalianSerieA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
                ('league', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.league', verbose_name='League')),
                ('team_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.italianclubs')),
            ],
            options={
                'verbose_name_plural': 'ItalianSerieA',
            },
        ),
        migrations.CreateModel(
            name='Bundesliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goalf', models.IntegerField()),
                ('goala', models.IntegerField()),
                ('point', models.IntegerField(default=0)),
                ('league', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='info.league', verbose_name='League')),
                ('team_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='info.germanclubs')),
            ],
            options={
                'verbose_name_plural': 'Bundesliga',
            },
        ),
    ]
