# Generated by Django 3.1 on 2021-02-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0092_auto_20210225_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ligue1',
            options={'verbose_name_plural': 'Ligue1'},
        ),
    ]
