# Generated by Django 3.1 on 2021-02-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0095_premiership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laliga',
        ),
    ]
