# Generated by Django 3.1 on 2021-02-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0097_laliga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundesliga',
        ),
    ]
