# Generated by Django 3.1 on 2021-02-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0099_bundesliga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiership',
            name='league',
        ),
        migrations.DeleteModel(
            name='Laliga',
        ),
        migrations.DeleteModel(
            name='Premiership',
        ),
    ]
