# Generated by Django 3.1 on 2021-02-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0100_auto_20210225_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bundesliga',
        ),
    ]
