# Generated by Django 3.1 on 2021-02-25 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0101_delete_bundesliga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='italianseriea',
            name='point',
        ),
        migrations.RemoveField(
            model_name='ligue1',
            name='point',
        ),
    ]
